# Generated by Django 2.0.8 on 2018-08-18 15:24

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_auto_20180812_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisepagequestions',
            name='page',
        ),
        migrations.AddField(
            model_name='exercisepage',
            name='questions',
            field=wagtail.core.fields.StreamField([('numeric_question', wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.RichTextBlock()), ('answer', wagtail.core.blocks.FloatBlock())]))], default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExercisePageQuestions',
        ),
    ]
