# Generated by Django 2.0.8 on 2018-08-18 20:39

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_auto_20180818_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisepage',
            name='questions',
            field=wagtail.core.fields.StreamField([('numeric', wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.RichTextBlock()), ('answer', wagtail.core.blocks.FloatBlock())])), ('multiple_choice', wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.RichTextBlock()), ('answers', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(label='Answer choice'))), ('correct_answer', wagtail.core.blocks.IntegerBlock(help_text='Index of the correct answer', required=True))]))]),
        ),
    ]
